/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _marioKartFont_h_
#define _marioKartFont_h_
//---------------------------------------------------------------------------------
extern const unsigned char marioKartFont[];
extern const int marioKartFont_size;
//---------------------------------------------------------------------------------
#endif //_marioKartFont_h_
//---------------------------------------------------------------------------------
